app/controllers/bookings_controller.rb
app/views/bookings/create.html.erb
app/views/bookings/destroy.html.erb
app/views/bookings/index.html.erb
app/views/bookings/new.html.erb
config/routes.rb
test/controllers/bookings_controller_test.rb

Soooohappy! That's for today's backend.

Added booking model and controller

---

app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/boats_controller.rb
app/views/boats/edit.html.erb
app/views/boats/index.html.erb
app/views/boats/new.html.erb
app/views/boats/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Hi team, the boats fundamental front-end view are ok, pls review

the boats basic views ready

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Fixed the migration issues and pushed my branch with homepage photo

Starting front end

---

app/controllers/bookings_controller.rb
app/views/boats/show.html.erb
app/views/bookings/create.html.erb
app/views/bookings/history.html.erb
app/views/bookings/new.html.erb
app/views/pages/home.html.erb
config/routes.rb

Add booking views and updated booking routes

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/views/boats/show.html.erb
app/views/layouts/application.html.erb

Hey team! Added a banner to the show page and also the card's components page.

Cards components

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/views/boats/show.html.erb

Hey team! Show page with only one picture is ready :)

Style card boat show pge

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/boats_controller.rb
app/policies/application_policy.rb
app/policies/boat_policy.rb
app/views/boats/index.html.erb
app/views/boats/show.html.erb
app/views/shared/_navbar.html.erb
test/policies/boat_policy_test.rb

Finally add pundit to boat
So glad '-^-^'

Add pundit

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/views/boats/new.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/registrations/new.html.erb

Hey team! Basic style in creating account page is done :)

Add new boat style

---

app/controllers/boats_controller.rb

Added a line to fix the Devise issue of not being able to see index/home unless user is logged in. Just a one line change, I'll merge it to master now.

Fixed issue with Devise of index/show pages requiring user login

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/application_controller.rb
app/controllers/boats_controller.rb
app/controllers/bookings_controller.rb
app/policies/application_policy.rb
app/policies/boat_policy.rb
app/views/boats/index.html.erb
app/views/boats/new.html.erb
app/views/boats/show.html.erb
app/views/bookings/create.html.erb
app/views/bookings/history.html.erb
app/views/bookings/new.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
test/policies/boat_policy_test.rb

I added the banner, cards and footer on the homepage. Still some styling tweaks but the structure is there.

Homepage is Done

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/application_controller.rb
app/controllers/boats_controller.rb
app/controllers/bookings_controller.rb
app/policies/application_policy.rb
app/policies/boat_policy.rb
app/views/boats/index.html.erb
app/views/boats/new.html.erb
app/views/boats/show.html.erb
app/views/bookings/create.html.erb
app/views/bookings/history.html.erb
app/views/bookings/new.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
test/policies/boat_policy_test.rb

Added banner, homepage cards, and footer.

Homepage Done

---

app/controllers/boats_controller.rb
app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
app/views/bookings/history.html.erb
app/views/layouts/application.html.erb
db/seeds.rb
test/policies/booking_policy_test.rb

hey team, added booking pundit~ @ERDeWees @ngerbauld

added booking pundit

---

Gemfile
Gemfile.lock
app/controllers/boats_controller.rb
app/models/boat.rb
app/models/user.rb
app/uploaders/photo_uploader.rb
app/views/boats/new.html.erb
app/views/boats/show.html.erb
app/views/shared/_navbar.html.erb
db/migrate/20190730142124_add_photo_to_boats.rb
db/migrate/20190730144002_add_photo_to_users.rb
db/migrate/20190730153813_remove_photo_from_users.rb
db/migrate/20190730154018_add_avatar_to_users.rb
db/schema.rb

Added image upload feature for boat add form. Tried to add avatar feature, but failed to make it work. Avatar column is still in the Users table, but other avatar related code have been commented out.

Add img upload

---

app/controllers/boats_controller.rb

Hope this resolves the image upload issue

Added permission for photo_cache

---

app/controllers/boats_controller.rb
app/views/boats/index.html.erb

Limited index page to 6 boats with correct photos

---

app/views/boats/index.html.erb

Responsiveness should be fixed now, but images will not have original aspect ratio

Fixed index page photo bug

---

app/views/bookings/history.html.erb
app/views/bookings/new.html.erb

Team, booking backend is ready.
JIAYOU

Added booking new and history backend

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/views/boats/index.html.erb
app/views/shared/_navbar.html.erb

Navbar update

---

app/views/devise/sessions/new.html.erb

Login page mirrors sign up page styling

Sign in page

---

app/models/booking.rb

Now the start date can no longer be before today
and
the end date must be after start date

added booking logic

---

app/assets/stylesheets/components/_booking_card.scss
app/assets/stylesheets/components/_index.scss
app/views/bookings/history.html.erb

hey team! booking confirmation page it is a little better :)

Booking page cards

---

app/views/bookings/history.html.erb

fixed reservation

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/boats_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/boats/_info_window.html.erb
app/views/layouts/application.html.erb

Map with window and link and avatar!

map with window and link

---

app/assets/stylesheets/components/_index.scss

fixed index.scss typo

---

app/models/booking.rb
app/views/bookings/history.html.erb
app/views/bookings/index.html.erb
app/views/shared/_navbar.html.erb
db/schema.rb

1. Fix avatar bug
2. Add previous bookings to my bookings page, now looks great!
3. (muted the start_date and end_date validates for test and create data)
4. Finished my boats page backend part

Fix several bugs for navbar function

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/views/boats/index.html.erb
db/schema.rb

Made index page more responsive

---

app/views/shared/_navbar.html.erb

Removed email from navbar

---

app/assets/stylesheets/components/_container.scss
app/views/boats/index.html.erb

Mobiles now view this site as well as desktops

Further improved responsiveness for mobile screens

---

app/views/boats/index.html.erb

More index optimization

---

app/views/bookings/history.html.erb
app/views/bookings/index.html.erb

added my boats back-front end

---

app/policies/boat_policy.rb

Debugged show page for users who are not logged in

---

app/views/boats/index.html.erb

add button for tags

---

app/views/bookings/index.html.erb
app/views/shared/_navbar.html.erb
db/migrate/20190802073523_add_default_rating_to_reviews.rb
db/schema.rb

add default rating and star

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/views/boats/new.html.erb
app/views/shared/_navbar.html.erb

Fixed navbar and tags

---

app/controllers/boats_controller.rb
app/views/boats/show.html.erb

done with map
